# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotBox.ui'
#
# Created: Tue Mar 24 19:08:35 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(700, 671)
        Dialog.setStyleSheet(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 101, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.radioButton = QtGui.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(110, 200, 51, 22))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(160, 200, 51, 22))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.buttonGroup.addButton(self.radioButton_2)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.uploadFileButton = QtGui.QPushButton(Dialog)
        self.uploadFileButton.setGeometry(QtCore.QRect(110, 130, 91, 27))
        self.uploadFileButton.setObjectName(_fromUtf8("uploadFileButton"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 101, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.plotButton = QtGui.QPushButton(Dialog)
        self.plotButton.setGeometry(QtCore.QRect(10, 620, 191, 41))
        self.plotButton.setObjectName(_fromUtf8("plotButton"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 51, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit = QtGui.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(60, 90, 141, 21))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.calcWidget = QtGui.QWidget(Dialog)
        self.calcWidget.setGeometry(QtCore.QRect(210, 80, 261, 581))
        self.calcWidget.setObjectName(_fromUtf8("calcWidget"))
        self.acButton = QtGui.QPushButton(self.calcWidget)
        self.acButton.setGeometry(QtCore.QRect(210, 10, 41, 41))
        self.acButton.setObjectName(_fromUtf8("acButton"))
        self.coshButton = QtGui.QPushButton(self.calcWidget)
        self.coshButton.setGeometry(QtCore.QRect(160, 350, 41, 41))
        self.coshButton.setObjectName(_fromUtf8("coshButton"))
        self.rightParenthesisButton = QtGui.QPushButton(self.calcWidget)
        self.rightParenthesisButton.setGeometry(QtCore.QRect(60, 400, 41, 41))
        self.rightParenthesisButton.setObjectName(_fromUtf8("rightParenthesisButton"))
        self.eButton = QtGui.QPushButton(self.calcWidget)
        self.eButton.setGeometry(QtCore.QRect(10, 350, 41, 41))
        self.eButton.setObjectName(_fromUtf8("eButton"))
        self.Button_7 = QtGui.QPushButton(self.calcWidget)
        self.Button_7.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.Button_7.setObjectName(_fromUtf8("Button_7"))
        self.piButton = QtGui.QPushButton(self.calcWidget)
        self.piButton.setGeometry(QtCore.QRect(60, 350, 41, 41))
        self.piButton.setObjectName(_fromUtf8("piButton"))
        self.Button_4 = QtGui.QPushButton(self.calcWidget)
        self.Button_4.setGeometry(QtCore.QRect(10, 60, 41, 41))
        self.Button_4.setObjectName(_fromUtf8("Button_4"))
        self.Button_2 = QtGui.QPushButton(self.calcWidget)
        self.Button_2.setGeometry(QtCore.QRect(60, 110, 41, 41))
        self.Button_2.setObjectName(_fromUtf8("Button_2"))
        self.Button_1 = QtGui.QPushButton(self.calcWidget)
        self.Button_1.setGeometry(QtCore.QRect(10, 110, 41, 41))
        self.Button_1.setObjectName(_fromUtf8("Button_1"))
        self.tanButton = QtGui.QPushButton(self.calcWidget)
        self.tanButton.setGeometry(QtCore.QRect(210, 250, 41, 41))
        self.tanButton.setObjectName(_fromUtf8("tanButton"))
        self.Button_3 = QtGui.QPushButton(self.calcWidget)
        self.Button_3.setGeometry(QtCore.QRect(110, 110, 41, 41))
        self.Button_3.setObjectName(_fromUtf8("Button_3"))
        self.acoshButton = QtGui.QPushButton(self.calcWidget)
        self.acoshButton.setGeometry(QtCore.QRect(160, 400, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.acoshButton.setFont(font)
        self.acoshButton.setObjectName(_fromUtf8("acoshButton"))
        self.leftParenthesisButton = QtGui.QPushButton(self.calcWidget)
        self.leftParenthesisButton.setGeometry(QtCore.QRect(10, 400, 41, 41))
        self.leftParenthesisButton.setObjectName(_fromUtf8("leftParenthesisButton"))
        self.tanhButton = QtGui.QPushButton(self.calcWidget)
        self.tanhButton.setGeometry(QtCore.QRect(210, 350, 41, 41))
        self.tanhButton.setObjectName(_fromUtf8("tanhButton"))
        self.cosButton = QtGui.QPushButton(self.calcWidget)
        self.cosButton.setGeometry(QtCore.QRect(160, 250, 41, 41))
        self.cosButton.setObjectName(_fromUtf8("cosButton"))
        self.Button_8 = QtGui.QPushButton(self.calcWidget)
        self.Button_8.setGeometry(QtCore.QRect(60, 10, 41, 41))
        self.Button_8.setObjectName(_fromUtf8("Button_8"))
        self.sinhButton = QtGui.QPushButton(self.calcWidget)
        self.sinhButton.setGeometry(QtCore.QRect(110, 350, 41, 41))
        self.sinhButton.setObjectName(_fromUtf8("sinhButton"))
        self.absButton = QtGui.QPushButton(self.calcWidget)
        self.absButton.setGeometry(QtCore.QRect(60, 250, 41, 41))
        self.absButton.setObjectName(_fromUtf8("absButton"))
        self.atanhButton = QtGui.QPushButton(self.calcWidget)
        self.atanhButton.setGeometry(QtCore.QRect(210, 400, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.atanhButton.setFont(font)
        self.atanhButton.setObjectName(_fromUtf8("atanhButton"))
        self.xButton = QtGui.QPushButton(self.calcWidget)
        self.xButton.setGeometry(QtCore.QRect(10, 540, 90, 41))
        self.xButton.setObjectName(_fromUtf8("xButton"))
        self.Button_0 = QtGui.QPushButton(self.calcWidget)
        self.Button_0.setGeometry(QtCore.QRect(10, 160, 41, 41))
        self.Button_0.setObjectName(_fromUtf8("Button_0"))
        self.multButton = QtGui.QPushButton(self.calcWidget)
        self.multButton.setGeometry(QtCore.QRect(160, 60, 41, 41))
        self.multButton.setObjectName(_fromUtf8("multButton"))
        self.sqrButton = QtGui.QPushButton(self.calcWidget)
        self.sqrButton.setGeometry(QtCore.QRect(60, 300, 41, 41))
        self.sqrButton.setObjectName(_fromUtf8("sqrButton"))
        self.decimalButton = QtGui.QPushButton(self.calcWidget)
        self.decimalButton.setGeometry(QtCore.QRect(60, 160, 41, 41))
        self.decimalButton.setObjectName(_fromUtf8("decimalButton"))
        self.divButton = QtGui.QPushButton(self.calcWidget)
        self.divButton.setGeometry(QtCore.QRect(210, 60, 41, 41))
        self.divButton.setObjectName(_fromUtf8("divButton"))
        self.Button_6 = QtGui.QPushButton(self.calcWidget)
        self.Button_6.setGeometry(QtCore.QRect(110, 60, 41, 41))
        self.Button_6.setObjectName(_fromUtf8("Button_6"))
        self.expButton = QtGui.QPushButton(self.calcWidget)
        self.expButton.setGeometry(QtCore.QRect(110, 160, 41, 41))
        self.expButton.setObjectName(_fromUtf8("expButton"))
        self.equalButton = QtGui.QPushButton(self.calcWidget)
        self.equalButton.setGeometry(QtCore.QRect(210, 540, 41, 41))
        self.equalButton.setObjectName(_fromUtf8("equalButton"))
        self.xPowerYButton = QtGui.QPushButton(self.calcWidget)
        self.xPowerYButton.setGeometry(QtCore.QRect(160, 160, 41, 41))
        self.xPowerYButton.setObjectName(_fromUtf8("xPowerYButton"))
        self.sinButton = QtGui.QPushButton(self.calcWidget)
        self.sinButton.setGeometry(QtCore.QRect(110, 250, 41, 41))
        self.sinButton.setObjectName(_fromUtf8("sinButton"))
        self.Button_9 = QtGui.QPushButton(self.calcWidget)
        self.Button_9.setGeometry(QtCore.QRect(110, 10, 41, 41))
        self.Button_9.setObjectName(_fromUtf8("Button_9"))
        self.atanButton = QtGui.QPushButton(self.calcWidget)
        self.atanButton.setGeometry(QtCore.QRect(210, 300, 41, 41))
        self.atanButton.setObjectName(_fromUtf8("atanButton"))
        self.Button_5 = QtGui.QPushButton(self.calcWidget)
        self.Button_5.setGeometry(QtCore.QRect(60, 60, 41, 41))
        self.Button_5.setObjectName(_fromUtf8("Button_5"))
        self.delButton = QtGui.QPushButton(self.calcWidget)
        self.delButton.setGeometry(QtCore.QRect(160, 10, 41, 41))
        self.delButton.setObjectName(_fromUtf8("delButton"))
        self.xInverseButton = QtGui.QPushButton(self.calcWidget)
        self.xInverseButton.setGeometry(QtCore.QRect(210, 160, 41, 41))
        self.xInverseButton.setObjectName(_fromUtf8("xInverseButton"))
        self.yButton = QtGui.QPushButton(self.calcWidget)
        self.yButton.setGeometry(QtCore.QRect(110, 540, 91, 41))
        self.yButton.setObjectName(_fromUtf8("yButton"))
        self.asinButton = QtGui.QPushButton(self.calcWidget)
        self.asinButton.setGeometry(QtCore.QRect(110, 300, 41, 41))
        self.asinButton.setObjectName(_fromUtf8("asinButton"))
        self.subButton = QtGui.QPushButton(self.calcWidget)
        self.subButton.setGeometry(QtCore.QRect(210, 110, 41, 41))
        self.subButton.setObjectName(_fromUtf8("subButton"))
        self.asinhButton = QtGui.QPushButton(self.calcWidget)
        self.asinhButton.setGeometry(QtCore.QRect(110, 400, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.asinhButton.setFont(font)
        self.asinhButton.setObjectName(_fromUtf8("asinhButton"))
        self.sqrtButton = QtGui.QPushButton(self.calcWidget)
        self.sqrtButton.setGeometry(QtCore.QRect(10, 300, 41, 41))
        self.sqrtButton.setObjectName(_fromUtf8("sqrtButton"))
        self.logButton = QtGui.QPushButton(self.calcWidget)
        self.logButton.setGeometry(QtCore.QRect(10, 250, 40, 41))
        self.logButton.setObjectName(_fromUtf8("logButton"))
        self.acosButton = QtGui.QPushButton(self.calcWidget)
        self.acosButton.setGeometry(QtCore.QRect(160, 300, 41, 41))
        self.acosButton.setObjectName(_fromUtf8("acosButton"))
        self.addButton = QtGui.QPushButton(self.calcWidget)
        self.addButton.setGeometry(QtCore.QRect(160, 110, 41, 41))
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.line = QtGui.QFrame(self.calcWidget)
        self.line.setGeometry(QtCore.QRect(-10, 0, 20, 621))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.addExprButton = QtGui.QPushButton(self.calcWidget)
        self.addExprButton.setGeometry(QtCore.QRect(10, 480, 241, 31))
        self.addExprButton.setObjectName(_fromUtf8("addExprButton"))
        self.expr = QtGui.QTextEdit(Dialog)
        self.expr.setGeometry(QtCore.QRect(50, 30, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.expr.setFont(font)
        self.expr.setStyleSheet(_fromUtf8(""))
        self.expr.setObjectName(_fromUtf8("expr"))
        self.lineEdit_y_min_3d = QtGui.QLineEdit(Dialog)
        self.lineEdit_y_min_3d.setEnabled(False)
        self.lineEdit_y_min_3d.setGeometry(QtCore.QRect(70, 320, 131, 20))
        self.lineEdit_y_min_3d.setObjectName(_fromUtf8("lineEdit_y_min_3d"))
        self.lineEdit_x_max_3d = QtGui.QLineEdit(Dialog)
        self.lineEdit_x_max_3d.setGeometry(QtCore.QRect(70, 290, 131, 20))
        self.lineEdit_x_max_3d.setObjectName(_fromUtf8("lineEdit_x_max_3d"))
        self.lineEdit_x_min_3d = QtGui.QLineEdit(Dialog)
        self.lineEdit_x_min_3d.setGeometry(QtCore.QRect(70, 260, 131, 20))
        self.lineEdit_x_min_3d.setObjectName(_fromUtf8("lineEdit_x_min_3d"))
        self.label_x_max_3d = QtGui.QLabel(Dialog)
        self.label_x_max_3d.setGeometry(QtCore.QRect(10, 290, 51, 17))
        self.label_x_max_3d.setObjectName(_fromUtf8("label_x_max_3d"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 450, 91, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_y_max_3d = QtGui.QLabel(Dialog)
        self.label_y_max_3d.setGeometry(QtCore.QRect(10, 350, 51, 17))
        self.label_y_max_3d.setObjectName(_fromUtf8("label_y_max_3d"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 390, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 420, 91, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox.setGeometry(QtCore.QRect(110, 450, 91, 21))
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.lineEdit_y_max_3d = QtGui.QLineEdit(Dialog)
        self.lineEdit_y_max_3d.setEnabled(False)
        self.lineEdit_y_max_3d.setGeometry(QtCore.QRect(70, 350, 131, 20))
        self.lineEdit_y_max_3d.setObjectName(_fromUtf8("lineEdit_y_max_3d"))
        self.label_y_min_3d = QtGui.QLabel(Dialog)
        self.label_y_min_3d.setGeometry(QtCore.QRect(10, 320, 51, 17))
        self.label_y_min_3d.setObjectName(_fromUtf8("label_y_min_3d"))
        self.colorButton = QtGui.QToolButton(Dialog)
        self.colorButton.setGeometry(QtCore.QRect(110, 421, 91, 20))
        self.colorButton.setObjectName(_fromUtf8("colorButton"))
        self.label_x_min_3d = QtGui.QLabel(Dialog)
        self.label_x_min_3d.setGeometry(QtCore.QRect(10, 260, 51, 17))
        self.label_x_min_3d.setObjectName(_fromUtf8("label_x_min_3d"))
        self.fileNameWidget = QtGui.QWidget(Dialog)
        self.fileNameWidget.setGeometry(QtCore.QRect(10, 160, 191, 21))
        self.fileNameWidget.setObjectName(_fromUtf8("fileNameWidget"))
        self.fileNameLabel = QtGui.QLabel(self.fileNameWidget)
        self.fileNameLabel.setGeometry(QtCore.QRect(0, 0, 161, 21))
        self.fileNameLabel.setText(_fromUtf8(""))
        self.fileNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fileNameLabel.setObjectName(_fromUtf8("fileNameLabel"))
        self.fileNameRemoveButton = QtGui.QPushButton(self.fileNameWidget)
        self.fileNameRemoveButton.setGeometry(QtCore.QRect(170, 0, 21, 21))
        self.fileNameRemoveButton.setObjectName(_fromUtf8("fileNameRemoveButton"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 230, 67, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineTypeWidget = QtGui.QWidget(Dialog)
        self.lineTypeWidget.setEnabled(True)
        self.lineTypeWidget.setGeometry(QtCore.QRect(10, 530, 191, 30))
        self.lineTypeWidget.setObjectName(_fromUtf8("lineTypeWidget"))
        self.lineTypeComboBox = QtGui.QComboBox(self.lineTypeWidget)
        self.lineTypeComboBox.setGeometry(QtCore.QRect(90, 0, 101, 30))
        self.lineTypeComboBox.setObjectName(_fromUtf8("lineTypeComboBox"))
        self.label_11 = QtGui.QLabel(self.lineTypeWidget)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.plotTypeWidget = QtGui.QWidget(Dialog)
        self.plotTypeWidget.setEnabled(True)
        self.plotTypeWidget.setGeometry(QtCore.QRect(10, 490, 191, 30))
        self.plotTypeWidget.setObjectName(_fromUtf8("plotTypeWidget"))
        self.comboBox = QtGui.QComboBox(self.plotTypeWidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 0, 101, 30))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.label_8 = QtGui.QLabel(self.plotTypeWidget)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.exprDimLabel = QtGui.QLabel(Dialog)
        self.exprDimLabel.setGeometry(QtCore.QRect(9, 36, 31, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.exprDimLabel.setFont(font)
        self.exprDimLabel.setObjectName(_fromUtf8("exprDimLabel"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(480, 81, 161, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tempListView = QtGui.QListView(Dialog)
        self.tempListView.setGeometry(QtCore.QRect(480, 114, 211, 353))
        self.tempListView.setObjectName(_fromUtf8("tempListView"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(480, 470, 111, 31))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.constantsTableWidget = QtGui.QTableWidget(Dialog)
        self.constantsTableWidget.setGeometry(QtCore.QRect(480, 500, 211, 160))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.constantsTableWidget.sizePolicy().hasHeightForWidth())
        self.constantsTableWidget.setSizePolicy(sizePolicy)
        self.constantsTableWidget.setMaximumSize(QtCore.QSize(211, 160))
        self.constantsTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.constantsTableWidget.setAutoScroll(False)
        self.constantsTableWidget.setAutoScrollMargin(0)
        self.constantsTableWidget.setObjectName(_fromUtf8("constantsTableWidget"))
        self.constantsTableWidget.setColumnCount(0)
        self.constantsTableWidget.setRowCount(0)
        self.opacityWidget = QtGui.QWidget(Dialog)
        self.opacityWidget.setEnabled(True)
        self.opacityWidget.setGeometry(QtCore.QRect(10, 570, 191, 30))
        self.opacityWidget.setObjectName(_fromUtf8("opacityWidget"))
        self.opacityComboBox = QtGui.QComboBox(self.opacityWidget)
        self.opacityComboBox.setGeometry(QtCore.QRect(90, 0, 101, 30))
        self.opacityComboBox.setObjectName(_fromUtf8("opacityComboBox"))
        self.label_13 = QtGui.QLabel(self.opacityWidget)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.expr, self.lineEdit)
        Dialog.setTabOrder(self.lineEdit, self.uploadFileButton)
        Dialog.setTabOrder(self.uploadFileButton, self.fileNameRemoveButton)
        Dialog.setTabOrder(self.fileNameRemoveButton, self.radioButton)
        Dialog.setTabOrder(self.radioButton, self.radioButton_2)
        Dialog.setTabOrder(self.radioButton_2, self.lineEdit_x_min_3d)
        Dialog.setTabOrder(self.lineEdit_x_min_3d, self.lineEdit_x_max_3d)
        Dialog.setTabOrder(self.lineEdit_x_max_3d, self.lineEdit_y_min_3d)
        Dialog.setTabOrder(self.lineEdit_y_min_3d, self.lineEdit_y_max_3d)
        Dialog.setTabOrder(self.lineEdit_y_max_3d, self.colorButton)
        Dialog.setTabOrder(self.colorButton, self.doubleSpinBox)
        Dialog.setTabOrder(self.doubleSpinBox, self.lineTypeComboBox)
        Dialog.setTabOrder(self.lineTypeComboBox, self.comboBox)
        Dialog.setTabOrder(self.comboBox, self.plotButton)
        Dialog.setTabOrder(self.plotButton, self.Button_7)
        Dialog.setTabOrder(self.Button_7, self.Button_8)
        Dialog.setTabOrder(self.Button_8, self.Button_9)
        Dialog.setTabOrder(self.Button_9, self.delButton)
        Dialog.setTabOrder(self.delButton, self.acButton)
        Dialog.setTabOrder(self.acButton, self.Button_4)
        Dialog.setTabOrder(self.Button_4, self.Button_5)
        Dialog.setTabOrder(self.Button_5, self.Button_6)
        Dialog.setTabOrder(self.Button_6, self.multButton)
        Dialog.setTabOrder(self.multButton, self.divButton)
        Dialog.setTabOrder(self.divButton, self.Button_1)
        Dialog.setTabOrder(self.Button_1, self.Button_2)
        Dialog.setTabOrder(self.Button_2, self.Button_3)
        Dialog.setTabOrder(self.Button_3, self.addButton)
        Dialog.setTabOrder(self.addButton, self.subButton)
        Dialog.setTabOrder(self.subButton, self.Button_0)
        Dialog.setTabOrder(self.Button_0, self.decimalButton)
        Dialog.setTabOrder(self.decimalButton, self.expButton)
        Dialog.setTabOrder(self.expButton, self.xPowerYButton)
        Dialog.setTabOrder(self.xPowerYButton, self.xInverseButton)
        Dialog.setTabOrder(self.xInverseButton, self.logButton)
        Dialog.setTabOrder(self.logButton, self.absButton)
        Dialog.setTabOrder(self.absButton, self.sinButton)
        Dialog.setTabOrder(self.sinButton, self.cosButton)
        Dialog.setTabOrder(self.cosButton, self.tanButton)
        Dialog.setTabOrder(self.tanButton, self.sqrtButton)
        Dialog.setTabOrder(self.sqrtButton, self.sqrButton)
        Dialog.setTabOrder(self.sqrButton, self.asinButton)
        Dialog.setTabOrder(self.asinButton, self.acosButton)
        Dialog.setTabOrder(self.acosButton, self.atanButton)
        Dialog.setTabOrder(self.atanButton, self.eButton)
        Dialog.setTabOrder(self.eButton, self.piButton)
        Dialog.setTabOrder(self.piButton, self.sinhButton)
        Dialog.setTabOrder(self.sinhButton, self.coshButton)
        Dialog.setTabOrder(self.coshButton, self.tanhButton)
        Dialog.setTabOrder(self.tanhButton, self.leftParenthesisButton)
        Dialog.setTabOrder(self.leftParenthesisButton, self.rightParenthesisButton)
        Dialog.setTabOrder(self.rightParenthesisButton, self.asinhButton)
        Dialog.setTabOrder(self.asinhButton, self.acoshButton)
        Dialog.setTabOrder(self.acoshButton, self.atanhButton)
        Dialog.setTabOrder(self.atanhButton, self.xButton)
        Dialog.setTabOrder(self.xButton, self.yButton)
        Dialog.setTabOrder(self.yButton, self.equalButton)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Set Plot Details", None))
        self.label_3.setText(_translate("Dialog", "Plot Settings:", None))
        self.radioButton.setText(_translate("Dialog", "2D", None))
        self.radioButton_2.setText(_translate("Dialog", "3D", None))
        self.label_2.setText(_translate("Dialog", "Expression :", None))
        self.uploadFileButton.setText(_translate("Dialog", "Upload File", None))
        self.label_4.setText(_translate("Dialog", "Plot from File:", None))
        self.plotButton.setText(_translate("Dialog", "Plot", None))
        self.label_7.setText(_translate("Dialog", "Name:", None))
        self.acButton.setText(_translate("Dialog", "AC", None))
        self.coshButton.setText(_translate("Dialog", "cosh", None))
        self.rightParenthesisButton.setText(_translate("Dialog", ")", None))
        self.eButton.setText(_translate("Dialog", "e", None))
        self.Button_7.setText(_translate("Dialog", "7", None))
        self.piButton.setText(_translate("Dialog", "π", None))
        self.Button_4.setText(_translate("Dialog", "4", None))
        self.Button_2.setText(_translate("Dialog", "2", None))
        self.Button_1.setText(_translate("Dialog", "1", None))
        self.tanButton.setText(_translate("Dialog", "tan", None))
        self.Button_3.setText(_translate("Dialog", "3", None))
        self.acoshButton.setText(_translate("Dialog", "acosh", None))
        self.leftParenthesisButton.setText(_translate("Dialog", "(", None))
        self.tanhButton.setText(_translate("Dialog", "tanh", None))
        self.cosButton.setText(_translate("Dialog", "cos", None))
        self.Button_8.setText(_translate("Dialog", "8", None))
        self.sinhButton.setText(_translate("Dialog", "sinh", None))
        self.absButton.setText(_translate("Dialog", "abs", None))
        self.atanhButton.setText(_translate("Dialog", "atanh", None))
        self.xButton.setText(_translate("Dialog", "x", None))
        self.Button_0.setText(_translate("Dialog", "0", None))
        self.multButton.setText(_translate("Dialog", "*", None))
        self.sqrButton.setText(_translate("Dialog", "^2", None))
        self.decimalButton.setText(_translate("Dialog", ".", None))
        self.divButton.setText(_translate("Dialog", "/", None))
        self.Button_6.setText(_translate("Dialog", "6", None))
        self.expButton.setText(_translate("Dialog", "EXP", None))
        self.equalButton.setText(_translate("Dialog", "=", None))
        self.xPowerYButton.setText(_translate("Dialog", "^", None))
        self.sinButton.setText(_translate("Dialog", "sin", None))
        self.Button_9.setText(_translate("Dialog", "9", None))
        self.atanButton.setText(_translate("Dialog", "atan", None))
        self.Button_5.setText(_translate("Dialog", "5", None))
        self.delButton.setText(_translate("Dialog", "DEL", None))
        self.xInverseButton.setText(_translate("Dialog", "^-1", None))
        self.yButton.setText(_translate("Dialog", "y", None))
        self.asinButton.setText(_translate("Dialog", "asin", None))
        self.subButton.setText(_translate("Dialog", "-", None))
        self.asinhButton.setText(_translate("Dialog", "asinh", None))
        self.sqrtButton.setText(_translate("Dialog", "sqrt", None))
        self.logButton.setText(_translate("Dialog", "log", None))
        self.acosButton.setText(_translate("Dialog", "acos", None))
        self.addButton.setText(_translate("Dialog", "+", None))
        self.addExprButton.setText(_translate("Dialog", "Add Expression", None))
        self.label_x_max_3d.setText(_translate("Dialog", "X - Max", None))
        self.label_6.setText(_translate("Dialog", "Graph Width :", None))
        self.label_y_max_3d.setText(_translate("Dialog", "Y - Max", None))
        self.label_5.setText(_translate("Dialog", "Display Settings:", None))
        self.label.setText(_translate("Dialog", "Graph Color :", None))
        self.label_y_min_3d.setText(_translate("Dialog", "Y - Min", None))
        self.colorButton.setText(_translate("Dialog", "...", None))
        self.label_x_min_3d.setText(_translate("Dialog", "X - Min", None))
        self.fileNameRemoveButton.setText(_translate("Dialog", "x", None))
        self.label_9.setText(_translate("Dialog", "Ranges:", None))
        self.label_11.setText(_translate("Dialog", "Line Type:", None))
        self.label_8.setText(_translate("Dialog", "Plot Type:", None))
        self.exprDimLabel.setText(_translate("Dialog", "Y = ", None))
        self.label_10.setText(_translate("Dialog", "Choose an expression :", None))
        self.label_12.setText(_translate("Dialog", "Set Constants :", None))
        self.label_13.setText(_translate("Dialog", "Opacity", None))

